"""Add CMS models

Revision ID: 1bbd567e0600
Revises: 004_catalog_foundation
Create Date: 2026-03-30 12:59:53.123154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbd567e0600'
down_revision = '004_catalog_foundation'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('block_type', sa.String(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_blocks_block_type'), ['block_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_blocks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_blocks_name'), ['name'], unique=True)

    op.create_table('section_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('section_type', sa.String(), nullable=False),
    sa.Column('default_config_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('section_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_templates_id'), ['id'], unique=False)

    op.create_table('seo_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_title', sa.String(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.String(), nullable=True),
    sa.Column('robots_directive', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seo_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seo_entries_id'), ['id'], unique=False)

    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('featured_image', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('read_time', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('seo_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seo_id'], ['seo_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_posts_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_blog_posts_status'), ['status'], unique=False)

    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('seo_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['seo_id'], ['seo_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_pages_status'), ['status'], unique=False)

    op.create_table('page_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_sections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_sections_page_id'), ['page_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_product_type'), ['product_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_product_type'))

    with op.batch_alter_table('page_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_sections_page_id'))
        batch_op.drop_index(batch_op.f('ix_page_sections_id'))

    op.drop_table('page_sections')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_status'))
        batch_op.drop_index(batch_op.f('ix_pages_slug'))
        batch_op.drop_index(batch_op.f('ix_pages_id'))

    op.drop_table('pages')
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_posts_status'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_slug'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_id'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_category'))
        batch_op.drop_index(batch_op.f('ix_blog_posts_author_id'))

    op.drop_table('blog_posts')
    with op.batch_alter_table('seo_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seo_entries_id'))

    op.drop_table('seo_entries')
    with op.batch_alter_table('section_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_templates_id'))

    op.drop_table('section_templates')
    with op.batch_alter_table('content_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_blocks_name'))
        batch_op.drop_index(batch_op.f('ix_content_blocks_id'))
        batch_op.drop_index(batch_op.f('ix_content_blocks_block_type'))

    op.drop_table('content_blocks')
    # ### end Alembic commands ###
